export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const RETRIEVE_CATEGORY = "RETRIEVE_CATEGORY";
export const RETRIEVE_CATEGORY_ID = "RETRIEVE_CATEGORY_ID";